### ISSUE TITLE
Amalgamate the negative suspense records

### ISSUE THREAD

**Issue by zoecrosby** [LocalGovIMS/localgov-ims#160]
When posting suspense transactions to the correct place if 1 suspense item is posted to two places then 4 transactions are create, 2 negative and 2 positive. This causes a problem for the exports to SAP GL and the suspense items have to be amalgamated in the export. The easy solution is to create 3 transactions, the 2 new postings and 1 negative suspense for the whole amount.

The same applies when adding a credit note, if a credit note of £40 is added to the suspense item of £30 and then allocated to 4 transactions of £20 x3 and £10 , 8 transactions are created when ideally only 6 should be

**Comment by bmbc-dev-detec** [comment]
Hi @zoecrosby - this has been completed now
