### ISSUE TITLE
Link credit notes to suspense items

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#18]
There is a scenario that has cropped up where it's not possible to see all the actions taken (transactions created) during suspense allocation..

1. Pick a suspense item, for say, £100.

2. Add a credit note for £100.

3. Journal the £200 to two places, both for £100.

Clicking the suspense item will only show one journalled transaction (which from a monetary point of view is fine - because you can only journal £100 from the suspense item). However, they want, in this scenario, for the credit note to also show.

We can achieve this by storing the entry for this transaction in the SuspenseTransactionProcessed table, with a zero value. The creation of these table entries is done in the SuspenseJournalAllocationStragegy::Distribute method. (which is quite complicated).

However, this creates another problem - what value do we show for it? This is important, because it will appear on the Suspense details page.

Say we show the positive total of the journals - £200, that would be £100 more than the suspense total, which will be misleading. IT is alsmo misleading in that £200 hasn't been journalled from the Suspense item,only £100 has, the other £100 was solely from a credit note.

On another note - as it currently stands, each suspense journal transaction has the same Transfer_Reference value - as a Suspense item must be allocated in one go. If we used that, we could load all TransactionProcessed records that were created during the Suspense journal allocation process. We could show some as credit notes, and others as journals etc.

This wouldn't require altering the Suspense allocation process, but, is t future proof? What happens if the want to allow part allocation of a suspense item? In that scenario there will be multiple Transfer_References in the TrnasactionProcessed records that link to the Suspense item.

**Comment by bmbc-dev-detec** [comment]
Resolved as part of #160
