### ISSUE TITLE
Amend CI/CD pipelines for demo site to pull from repo

### ISSUE THREAD

**Issue by bmbc-richki** [LocalGovIMS/localgov-ims#187]
The demo instance of LocalGov IMS is a version populated from our old DevOps repository. We need to either update our existing deployment pipelines to have them pull from the new GitHub repository OR create new deployment pipelines in GitHub to push to the demo site.

**Comment by bmbc-dev-detec** [comment]
Once the demo site has been moved to Dorset the publishing wont be done via CI/CD pipelines, it will be done manually, so I'm closing this.
