### ISSUE TITLE
SKIP option for import rules

### ISSUE THREAD

**Issue by zoecrosby** [LocalGovIMS/localgov-ims#190]
Add the option SKIP to the Set drop down in the import action rules
When this action rule is added, the transaction with this action will be ignored and not loaded into the system. Obviously if this rule is applied then no other rules are relevant

**Comment by bmbc-dev-detec** [comment]
Hi @zoecrosby,
Can you provide more info please?:
- Why do transactions need to be skipped?
- How are they identified?

**Comment by zoecrosby** [comment]
All the imports that we do, including card payments, the actual money goes into our bank account as a total sum daily/monthly depending on the payment type. The barclays import file contains these sum transactions eg total for all moto payments, obviously we have already accounted for this money as we have been taking the individual transactions so we need to ignore this total sum and not post it any where otherwise it would be double counting. therefore we have importcontidions like SUBSTRING(AccountRef, 1,8) = '12345641' and SUBSTRING(Narrative,1,16) = 'BGC MERCHANT RES' then the output condition is to SKIP this record (ignore it) as the money has already been accounted for by the individual transactions

**Comment by zoecrosby** [comment]
We have agreed to add a new database to the barclays import process so that rules that have not been currently developed in the IMS can be added to this specific barclays import database as sql statements are they currently are in the existing ims system.
