### ISSUE TITLE
Update import actions to include Split so a transaction can be split on import

### ISSUE THREAD

**Issue by zoecrosby** [LocalGovIMS/localgov-ims#191]
On the Import rules add the action SPLIT 
(when splitting an account it is dependant on the amount not changing on the import record of the rule will need changing)
We have 1 transaction from Boots that’s paying for 2 items so the import rules creates 2 records, it amends one and inserts another or splits the transaction?

**Comment by bmbc-dev-detec** [comment]
Hi @zoecrosby,
Let me know when you're free to discuss this, as it isn't clear how we need this to be achieved.

**Comment by zoecrosby** [comment]
Hi @bmbc-dev-detec ignore this issue, I've checked the import rule history and the rule has never been applied. It was created to split a certain amount to two accounts but due to the amount changing yearly its will have to be changed yearly so isnt worth doing.
