### ISSUE TITLE
Query Payment request

### ISSUE THREAD

**Issue by zoecrosby** [LocalGovIMS/localgov-ims#214]
Government Licence applications (ELMS) are completed via the government site. The customer completes the eform on the Gov.uk site when it comes to the payment it transfers to IMS. Once the payment has been taken and control passes back to Gov UK, then Gov UK calls Query Payment to validate a successful response. The process is locked down to IP address.

ALSO
DMC require the same Query payment process to confirm payments have been successful, but they require it via Authentication using credentials

**Extract below  from Dans handover notes**
Inside PaymentController there are two methods there two methods, one called CreatePayment andone called QueryPayment -CreatePayment is in use by Requestry already, QueryPayment is a new action for DMC -it needs basic auth adding onto that action (or similar) and then creds sharing with DMC via helpdesk job -this is because whilst we return a success/fail/cancel state in the response from the payment gateway these can't be trusted in isolation and that will let them do a server to server check.

**Comment by bmbc-dev-detec** [comment]
Is this the same as #277 @zoecrosby ?

**Comment by zoecrosby** [comment]
@bmbc-dev-detec No, but they are linked, #277 is referring to the CreatePayment request, this is on about the QueryPayment request. But we need to ensure that the QueryPayments request is also present

**Comment by bmbc-dev-detec** [comment]
This is BMBC specific work, in a separate code-base, so will be managed on another backlog
