### ISSUE TITLE
Change the Show All button to a dropdown with allocated, unallocated and all

### ISSUE THREAD

**Issue by bmbc-richki** [LocalGovIMS/localgov-ims#284]
Comment from user:

I don’t think I knew about the show all/show allocated change #232. Initially I thought it was a good idea but then realised that I do use the show allocated regularly when reviewing what’s been done so would have probably asked for it adding to the existing rather than replacing. Can it be changed to be show allocated, show un-allocated, show all?

**Comment by bmbc-dev-detec** [comment]
Completed
