### ISSUE TITLE
Date/Time validation on System Message edit/create page is using the wrong locale

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#30]
Navigate to the System Messages create/edit page
Input a date such as 30/06/2020
Try and save - client side validation will tell you the date/time is invalid

**Comment by bmbc-dev-detec** [comment]
HI @DanielAmbrose - Could you have a look at this one please?

**Comment by DanielAmbrose** [comment]
Looked at a few options but setting the type=datetime-local seems to be the nicest solution both from a code and UI point of view. My only potential concern is browser support: it looks like IE doesn't understand datetime inputs. Is this likely to be a problem?

**Comment by bmbc-dev-detec** [comment]
Possibly. Is the date/time picker a Semantic UI control? perhaps it's an issue with that?
If it is, maybe there are alternatives that are better?

**Comment by DanielAmbrose** [comment]
No, just a regular input as far as I know. I think I've used them before because the technology I was using had a fallback for IE etc.

**Comment by bmbc-dev-detec** [comment]
Closing after PR approval
