### ISSUE TITLE
self service payments add additional validation for the address

### ISSUE THREAD

**Issue by zoecrosby** [LocalGovIMS/localgov-ims#365]
We are having issues with card payment being rejected because the customer has put rubbish in the address fields when making a payment, for example the area/city field contained a phone number. It doesnt help that smartpayfuse also allows a phone number in the city field but then the card provider rejects the payment.

**Comment by bmbc-dev-detec** [comment]
Hi @zoecrosby  - do you have any suggests as to how we might resolve this?

**Comment by zoecrosby** [comment]
@bmbc-dev-detec the only option I can think of is to make sure the address fields has to have some alpha characters and not consist of just numbers (apart from the house number of course). Even this wouldn't stop the issue as the customer an over write these details on the card capture screen within Barclays but at least we will have done something to try and alleviate the problem

**Comment by bmbc-dev-detec** [comment]
Will be resolved in #379

**Comment by bmbc-dev-detec** [comment]
Completed
