### ISSUE TITLE
Identify when transactions have been transferred

### ISSUE THREAD

**Issue by zoecrosby** [LocalGovIMS/localgov-ims#368]
Please can an indicator such as **!** be added on the transactions screen to highlight where a transaction has been reallocated so that we are aware that the line item shown isn't the 'final destination' of the payment

**Comment by bmbc-dev-detec** [comment]
We don't currently have a way of navigating to the reallocation transaction - only from a reallocation transaction back to the source. 

This means we either need to introduce a new table to store the destination of reallocations (as a transaction can be reallocated to multiple places), or make an additional lookup to find any transactions with a source of any of the transactions for the list page we're viewing. We do a lookup similar to the second option when we're viewing a transaction on the details page - but it requries quite a few database calls, so will affect performance of the list page.

**Comment by bmbc-dev-detec** [comment]
Completed
