### ISSUE TITLE
Add 'soft block' or 'prompt' to consider if mop code has a metedata flag of Reversals

### ISSUE THREAD

**Issue by zoecrosby** [LocalGovIMS/localgov-ims#369]
mop codes 13 (DIRECT DEBIT - REVERSAL) and 25 (RETURNED CHEQUE) should only be used with negative amounts. therefore is we add a metedata tag of 'Reversals' can the system prompt the user to consider the amount if the amount is a positive

**Comment by bmbc-dev-detec** [comment]
Compelted
