### ISSUE TITLE
Standardise address format across pages and tables

### ISSUE THREAD

**Issue by zoecrosby** [LocalGovIMS/localgov-ims#379]
The Billing Address page when capturing a payment asks for House Number/Name, Street, Town/City, & Postal Code
The account holder table currently only has AddressLine1/AddressLine2 etc so when the Billing Address page is populated with the customers address the user has to cut and past the house number from the Street into the House Number field.
To make the process smoother for the user we will split the House number from the street on import of the account holder data, but to do this we will need the field HouseNumber or HouseNumberName adding to the account holder table

**Comment by bmbc-dev-detec** [comment]
After discussion the scope of this has changed. The requriements now are to make sure the AccountHolder, PendingTransaction and ProcessedTransaction tables have 5 address fields, as per the GOV.UK address pattern: https://design-system.service.gov.uk/patterns/addresses/

**Comment by bmbc-dev-detec** [comment]
Completed
