### ISSUE TITLE
Establish a button colour scheme throughout

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#47]
Feedback from the content review: On the button colours: greyed out buttons can suggest that the action isn’t available but they're used where that isn't the case. Establish a colour scheme, e.g. red = negative action, blue = positive action and apply it consistently throughout the application. 

For example the button to create a journal record is grey.

**Comment by bmbc-dev-detec** [comment]
Completed as part of #416
