### ISSUE TITLE
Ensure consistent display of error messages

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#50]
Feedback from the content review: Be consistent with error messages. Some are banners, some are in-line, and some are written in a different style. The most important aspects are that they don’t rely on colour to show that they’re an error message, they tell the user what they need to do (enter a reference number, for example), and that they look consistent across the service.

**Comment by bmbc-dev-detec** [comment]
Closing this as per W3C WCAG - notifications can be made either way.
