### ISSUE TITLE
Include a heading on the transaction search tools area

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#52]
Feedback from the content review: At the top of the transaction screen there are a number of fields and tools to search and filter the transaction list. Add a heading within the box to identify it's purpose. This will aid accessibility. Suggestion: Search transactions.

**Comment by bmbc-dev-detec** [comment]
A suitable option for now would be to add a header but to make it visually hidden.
Screen readers will still read it out.

**Comment by bmbc-dev-detec** [comment]
Going to run this past Callum at DXW before proceeding

**Comment by bmbc-dev-detec** [comment]
Completed
