### ISSUE TITLE
Enable overriding of stop messages by role so can still post to accounts when necessary

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#6]
Finance would like to be able to post payments to accounts that have stop messages
this means implementing a new role that can override the stop message and adding that role to their profile

**Comment by bmbc-dev-detec** [comment]
As of commit [#b123bc2fc66dbe6a45c60082cca3fb4866aee0f4](https://github.com/LocalGovIMS/localgov-ims/commit/b123bc2fc66dbe6a45c60082cca3fb4866aee0f4) Finance can make payments to accounts which are on stop.

Closing this as completed.
