### ISSUE TITLE
Ensure error messages include a required action

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#64]
Feedback from the content review. When error messages are presented, ensure they include an instruction as to what needs to happen next, e.g. You must enter a user name" rather than "User name is required". By writing in an instructional style, this aids accessibility and usability.

**Comment by bmbc-dev-detec** [comment]
This wasn't picked up in the October accessibility review.
These messages are defaults generated by the MVC framework. 
If this change is required it will be identified again in future accessibility testing (planned for later in Q1 2023).
As such I'm going to close this issue.
