### ISSUE TITLE
Create CRUD UI for customisable organisation details on VAT receipts

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#7]
Need VAT receipt to show organisation details when it's not a BMBC bill, rather than BMBC details which is technically not then permissable. For debtor accounts and housing rents accounts for BH for example, we need new email and print receipt. Applies to any organisation taking on the system.

**Comment by bmbc-dev-detec** [comment]
@zoecrosby - from a BMBC point of view is the following correct:

1. We need to add an Organisation entity. This will contain fields to represent the settings stored in the web.config app settings with a key name starting with 'Organisation'
2. One and only one of the organisations must be marked as the default.
3. We need a new system meta data key 'OrganisationId' for a Fund
4. Wherever we show organisation details within the app (e.g. short name - used in page title) we will pick the default Organisation and extract the values from that.
5. Wherever a receipt is generated (printed or emailed) we will check the fund the payment is for - try and retrieve an OrganisationId and use the details from the corresponding organisation to populate fields such as VAT number and address. If none is specified we will use the default organisation details.

Question: 
It is possible to make a payment for multiple items (funds) say a parking fine, a library charge and housing rents in one transaction (I believe it's possible to add up to 10 items to the payment basket). Each of these funds may be associated with a different organisation. How would BMBC expect that to be dealt with?

**Comment by bmbc-dev-detec** [comment]
Finance responded: 

> 'We cant do it for BMBC. We act as an agent for Berneslai homes and the money goes into our bank account so its our VAT details. We're not sure if the scenario would ever occur, you would have to have everything split if you had more than 1 organisation.'

It's not required for BMBC, and as no other council has yet requested it, I'll close this issue - it can be reopened or a new issue added in the future if it is needed.
